name: Build Windows EXE and Upload to Release

on:
  push:
    tags:
      - 'v*' # Only run on version tags like v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up ffmpeg
        run: |
          iex (irm ffmpeg.tc.ht)

      - name: Install Visual Studio 2022 Build Tools (if needed)
        uses: microsoft/setup-msbuild@v2

      - name: Create and activate venv
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          venv\Scripts\activate
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download models
        run: |
          mkdir models
          # Download your models here; replace the URLs with actual ones
          Invoke-WebRequest -Uri "https://example.com/GFPGANv1.4" -OutFile "models/GFPGANv1.4"
          Invoke-WebRequest -Uri "https://example.com/inswapper_128_fp16.onnx" -OutFile "models/inswapper_128_fp16.onnx"

      - name: Build EXE with PyInstaller
        run: |
          venv\Scripts\activate
          pyinstaller your_main_script.py --onefile --distpath build

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build\your_main_script.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}