name: Build Windows EXE and Upload to Release

on:
  push:
    branches:
      - main      

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up ffmpeg
        uses: jlumbroso/setup-ffmpeg@v1

      - name: Install Visual Studio 2022 Build Tools (if needed)
        uses: microsoft/setup-msbuild@v2

      - name: Create and activate venv
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          venv\Scripts\activate
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download models
        run: |
          mkdir models
          # Download your models here; replace the URLs with actual ones
          Invoke-WebRequest -Uri "https://huggingface.co/hacksider/DC/resolve/main/GFPGANv1.4.pth" -OutFile "models/GFPGANv1.4.pth"
          Invoke-WebRequest -Uri "https://huggingface.co/hacksider/DC/resolve/main/inswapper_128_fp16.onnx" -OutFile "models/inswapper_128_fp16.onnx"

      - name: Build EXE with PyInstaller
        run: |
          venv\Scripts\activate
          pyinstaller your_main_script.py --onefile --distpath build

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build\DC.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}